CI: azure
c_compiler: vs2019
channel_sources: conda-forge
channel_targets: conda-forge main
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: vs2019
extend_keys:
- ignore_build_only_deps
- ignore_version
- extend_keys
- pin_run_as_build
fmt: '10'
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
lua: '5'
numpy: '1.22'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '3.10'
r_base: '3.4'
spdlog: '1.12'
target_platform: win-64
vc: '14'
zlib: '1.2'
