# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Fri Aug 25 08:19:19 2023
# ------------------------------------------------

package:
  name: micromamba
  version: 1.5.0
source:
  - folder: mamba
    sha256: 0323e3a380d2a4b2bf20ef2520d271681480a6885b1505c3787e3683cbe58b17
    url: https://github.com/mamba-org/mamba/archive/refs/tags/micromamba-1.5.0.tar.gz
  - folder: vcpkg
    sha256: 1d1d3b4b3d1871211d3d7799babfb7443971ed9a51b9eb7018bb94dfdb387076
    url: https://github.com/microsoft/vcpkg/archive/8be970aaeaf19fd2663aaf5888478483f9742e55.tar.gz
build:
  ignore_run_exports_from:
    - fmt
    - python
    - spdlog
  number: '1'
  string: '1'
requirements:
  build:
    - 7zip 19.00 h2d74725_2
    - bzip2 1.0.8 h8ffe710_4
    - ca-certificates 2023.7.22 h56e8100_0
    - cmake 3.26.4 h1537add_0
    - curl 7.88.1 h68f0423_1
    - git 2.42.0 h57928b3_0
    - krb5 1.20.1 heb0366b_0
    - libcurl 7.88.1 h68f0423_1
    - libffi 3.4.2 h8ffe710_5
    - libsqlite 3.43.0 hcfcfb64_0
    - libssh2 1.11.0 h7dfc565_0
    - libzlib 1.2.13 hcfcfb64_5
    - ninja 1.11.1 h91493d7_0
    - openssl 3.1.2 hcfcfb64_0
    - python 3.10.12 h4de0772_0_cpython
    - tk 8.6.12 h8ffe710_0
    - tzdata 2023c h71feb2d_0
    - ucrt 10.0.22621.0 h57928b3_0
    - vc 14.3 h64f974e_17
    - vc14_runtime 14.36.32532 hfdfe4a8_17
    - vcpkg-tool 2023.03.14 h91bfe4b_0
    - vs2015_runtime 14.36.32532 h05e6639_17
    - vs2019_win-64 19.29.30139 he1865b1_17
    - vswhere 3.1.4 h57928b3_0
    - xz 5.2.6 h8d14728_0
    - zlib 1.2.13 hcfcfb64_5
  host:
    - cli11 2.3.2 h63175ca_0
    - cpp-expected 1.1.0 h91493d7_0
    - fmt 10.1.0 h181d51b_0
    - nlohmann_json 3.11.2 h39d44d4_0
    - spdlog 1.12.0 h64d2f7d_1
    - ucrt 10.0.22621.0 h57928b3_0
    - vc 14.3 h64f974e_17
    - vc14_runtime 14.36.32532 hfdfe4a8_17
    - vs2015_runtime 14.36.32532 h05e6639_17
    - winreg 6.1.0 h57928b3_1
  run:
    - ucrt >=10.0.20348.0
    - vc >=14.2,<15
    - vc14_runtime >=14.29.30139
test:
  commands:
    - if not exist %LIBRARY_BIN%\micromamba.exe (exit 1)
    - micromamba.exe --help
    - mkdir %TEMP%\mamba
    - set "MAMBA_ROOT_PREFIX=%TEMP%\mamba"
    - micromamba.exe create -n test --override-channels -c conda-forge --yes python=3.9
    - '%MAMBA_ROOT_PREFIX%\envs\test\python.exe --version'
    - '%MAMBA_ROOT_PREFIX%\envs\test\python.exe -c "import os"'
about:
  dev_url: https://github.com/mamba-org/mamba
  home: https://github.com/mamba-org/mamba
  license: BSD-3-Clause AND MIT AND OpenSSL
  license_family: BSD
  license_file:
    - CLI11_LICENSE.txt
    - CURL_LICENSE.txt
    - C_ARES_LICENSE.txt
    - FMT_LICENSE.txt
    - KRB5_LICENSE.txt
    - LIBARCHIVE_LICENSE.txt
    - LIBEV_LICENSE.txt
    - LIBLZ4_LICENSE.txt
    - LIBNGHTTP2_LICENSE.txt
    - LIBOPENSSL_3_LICENSE.txt
    - LIBOPENSSL_LICENSE.txt
    - LIBSOLV_LICENSE.txt
    - NLOHMANN_JSON_LICENSE.txt
    - REPROC_LICENSE.txt
    - SPDLOG_LICENSE.txt
    - TL_EXPECTED_LICENSE.txt
    - ZSTD_LICENSE.txt
    - mamba/LICENSE
  summary: Micromamba is a tiny version of mamba, the fast conda package installer.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - mariusvniekerk
    - pavelzw
    - wolfv
