# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Fri Aug 25 08:19:14 2023
# ------------------------------------------------

package:
  name: micromamba
  version: 1.5.0
source:
  - folder: mamba
    sha256: 0323e3a380d2a4b2bf20ef2520d271681480a6885b1505c3787e3683cbe58b17
    url: https://github.com/mamba-org/mamba/archive/refs/tags/micromamba-1.5.0.tar.gz
build:
  ignore_run_exports_from:
    - fmt
    - gcc_linux-64 12.*
    - gxx_linux-64 12.*
    - libarchive-minimal-static
    - libcurl
    - openssl
    - reproc-cpp
    - spdlog
  number: '1'
  string: '1'
requirements:
  build:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - binutils_impl_linux-64 2.40 hf600244_0
    - binutils_linux-64 2.40 hbdbef99_1
    - bzip2 1.0.8 h7f98852_4
    - c-ares 1.19.1 hd590300_0
    - ca-certificates 2023.7.22 hbcca054_0
    - cmake 3.26.4 hcfe8598_0
    - expat 2.5.0 hcb278e6_1
    - gcc_impl_linux-64 12.3.0 he2b93b0_0
    - gcc_linux-64 12.3.0 h76fc315_1
    - gxx_impl_linux-64 12.3.0 he2b93b0_0
    - gxx_linux-64 12.3.0 h8a814eb_1
    - kernel-headers_linux-64 2.6.32 he073ed8_16
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.21.2 h659d440_0
    - ld_impl_linux-64 2.40 h41732ed_0
    - libcurl 8.2.1 hca28451_0
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 h516909a_1
    - libexpat 2.5.0 hcb278e6_1
    - libgcc-devel_linux-64 12.3.0 h8bca6fd_0
    - libgcc-ng 13.1.0 he5830b7_0
    - libgomp 13.1.0 he5830b7_0
    - libnghttp2 1.52.0 h61bc06f_0
    - libsanitizer 12.3.0 h0f45ef3_0
    - libssh2 1.11.0 h0841786_0
    - libstdcxx-devel_linux-64 12.3.0 h8bca6fd_0
    - libstdcxx-ng 13.1.0 hfd8a6a1_0
    - libuv 1.44.2 hd590300_1
    - libzlib 1.2.13 hd590300_5
    - ncurses 6.4 hcb278e6_0
    - ninja 1.11.1 h924138e_0
    - openssl 3.1.2 hd590300_0
    - rhash 1.4.3 hd590300_1
    - sysroot_linux-64 2.12 he073ed8_16
    - xz 5.2.6 h166bdaf_0
    - zlib 1.2.13 hd590300_5
    - zstd 1.5.2 hfc55251_7
  host:
    - _libgcc_mutex 0.1 conda_forge
    - _openmp_mutex 4.5 2_gnu
    - bzip2 1.0.8 h7f98852_4
    - c-ares 1.19.1 hd590300_0
    - c-ares-static 1.19.1 hd590300_0
    - ca-certificates 2023.7.22 hbcca054_0
    - cli11 2.3.2 hcb278e6_0
    - cpp-expected 1.1.0 hf52228f_0
    - fmt 10.1.0 h00ab1b0_0
    - keyutils 1.6.1 h166bdaf_0
    - krb5 1.20.1 h81ceb04_0
    - krb5-static 1.20.1 h81ceb04_0
    - libarchive-minimal-static 3.6.2 h2b6973b_1
    - libcurl 7.88.1 hdc1c0ab_1
    - libcurl-static 7.88.1 hdc1c0ab_1
    - libedit 3.1.20191231 he28a2e2_2
    - libev 4.33 h516909a_1
    - libev-static 4.33 h516909a_1
    - libgcc-ng 13.1.0 he5830b7_0
    - libgomp 13.1.0 he5830b7_0
    - libnghttp2 1.52.0 h61bc06f_0
    - libnghttp2-static 1.52.0 h9cb18e5_0
    - libopenssl-static 3.1.2 hd590300_0
    - libsolv 0.7.24 hfc55251_3
    - libsolv-static 0.7.24 hfc55251_3
    - libssh2 1.11.0 h0841786_0
    - libssh2-static 1.11.0 h0841786_0
    - libstdcxx-ng 13.1.0 hfd8a6a1_0
    - libzlib 1.2.13 hd590300_5
    - lz4-c-static 1.9.4 ha770c72_0
    - ncurses 6.4 hcb278e6_0
    - nlohmann_json 3.11.2 h27087fc_0
    - openssl 3.1.2 hd590300_0
    - reproc 14.2.4 h0b41bf4_0
    - reproc-cpp 14.2.4 hcb278e6_0
    - reproc-cpp-static 14.2.4 hcb278e6_0
    - reproc-static 14.2.4 h0b41bf4_0
    - spdlog 1.12.0 hd2e6256_1
    - xz 5.2.6 h166bdaf_0
    - xz-static 5.2.6 h166bdaf_0
    - yaml-cpp 0.7.0 h27087fc_2
    - yaml-cpp-static 0.7.0 h27087fc_2
    - zlib 1.2.13 hd590300_5
    - zstd 1.5.2 hfc55251_7
    - zstd-static 1.5.2 h59595ed_7
  run:
    - libzlib >=1.2.13,<1.3.0a0
test:
  commands:
    - test -f "${PREFIX}/bin/micromamba"
    - micromamba --help
    - export MAMBA_ROOT_PREFIX="$(mktemp -d)"
    - micromamba create -n test --override-channels -c conda-forge --yes python=3.9
    - '"${MAMBA_ROOT_PREFIX}/envs/test/bin/python" --version'
    - '"${MAMBA_ROOT_PREFIX}/envs/test/bin/python" -c "import os"'
about:
  dev_url: https://github.com/mamba-org/mamba
  home: https://github.com/mamba-org/mamba
  license: BSD-3-Clause AND MIT AND OpenSSL
  license_family: BSD
  license_file:
    - CLI11_LICENSE.txt
    - CURL_LICENSE.txt
    - C_ARES_LICENSE.txt
    - FMT_LICENSE.txt
    - KRB5_LICENSE.txt
    - LIBARCHIVE_LICENSE.txt
    - LIBEV_LICENSE.txt
    - LIBLZ4_LICENSE.txt
    - LIBNGHTTP2_LICENSE.txt
    - LIBOPENSSL_3_LICENSE.txt
    - LIBOPENSSL_LICENSE.txt
    - LIBSOLV_LICENSE.txt
    - NLOHMANN_JSON_LICENSE.txt
    - REPROC_LICENSE.txt
    - SPDLOG_LICENSE.txt
    - TL_EXPECTED_LICENSE.txt
    - ZSTD_LICENSE.txt
    - mamba/LICENSE
  summary: Micromamba is a tiny version of mamba, the fast conda package installer.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - mariusvniekerk
    - pavelzw
    - wolfv
