name: Sync up devchat packages

on:
  # workflow_dispatch:
  push:
    branches:
      - ci

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2
    #   with:
    #     ref: main

    # - name: Create new branch
    #   run: |
    #     git checkout -b new-branch

    - name: Setup micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: "1.5.8-0"
        init-shell: bash
        environment-name: devchat_no_binary
        create-args: >-
          python=3.8
      
    - name: Checkout devchat repository to a temporary directory
      uses: actions/checkout@v2
      with:
        repository: devchat-ai/devchat
        path: ./temp-devchat
    
    - name: Install devchat dependencies
      shell: micromamba-shell {0}
      run: |
        echo ">>>>>>>>>> check current path"
        pwd
        ls
        echo ">>>>>>>>>> Check site packages before install"
        ls $SITE_PACKAGES
        SITE_PACKAGES=$(python -c "import site; print(site.getsitepackages()[0])")
        echo $SITE_PACKAGES
        cd ./temp-devchat
        pip list
        echo ">>>> Installing devchat dependencies"
        pip install --no-binary :all: "pydantic<2"
        pip install charset-normalizer --no-binary :all:
        pip install git+https://github.com/yangbobo2021/tiktoken.git
        pip install .
        echo ">>>>>>>>>>>> Finish devchat dependencies"
        pip list
        echo ">>>>>>>>>>>> Check site packages after install"
        ls $SITE_PACKAGES
        

    # - name: Commit changes
    #   run: |
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git commit -am "Sync up devchat packages"

    # - name: Push changes
    #   run: |
    #     git push origin new-branch

    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v3
    #   with:
    #     title: "Sync up devchat packages"
    #     branch: "new-branch"
    #     body: "This PR is auto-generated by GitHub Action. It syncs up the devchat packages."