name: Sync up devchat packages

on:
  # workflow_dispatch:
  push:
    branches:
      - ci

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    # - name: Create new branch
    #   run: |
    #     git checkout -b update-packages-$(date +'%Y%m%d-%H%M%S')

    - name: Setup micromamba
      uses: mamba-org/setup-micromamba@v1
      with:
        micromamba-version: "1.5.8-0"
        init-shell: bash
        environment-name: devchat_no_binary
        create-args: >-
          python=3.8
      
    - name: Checkout devchat repository to a temporary directory
      uses: actions/checkout@v4
      with:
        repository: devchat-ai/devchat
        path: ./temp/devchat-repo
    
    - name: Install devchat dependencies
      shell: micromamba-shell {0}
      run: |
        echo ">>>>>>>>>> check current path"
        pwd
        ls
        echo ">>>>>>>>>> Check site packages before install"
        SITE_PACKAGES=$(python -c "import site; print(site.getsitepackages()[0])")
        ls -al $SITE_PACKAGES
        echo $SITE_PACKAGES
        ITEMS_BEFORE=$(mktemp)
        ls $SITE_PACKAGES > "$ITEMS_BEFORE"
        cat "$ITEMS_BEFORE"
        echo ">>>>>>>>>> Start installing..."
        cd ./temp/devchat-repo
        pip list
        echo ">>>> Installing devchat dependencies"
        pip install --no-binary :all: "pydantic<2"
        pip install charset-normalizer --no-binary :all:
        pip install git+https://github.com/yangbobo2021/tiktoken.git
        pip install .
        echo ">>>>>>>>>>>> Finish devchat dependencies"
        pip list
        echo ">>>>>>>>>>>> Check site packages after install"
        ls $SITE_PACKAGES
        ITEMS_AFTER=$(mktemp)
        echo ">>>>>>>>>>>>>>>>>>>>>>"
        ls $SITE_PACKAGES > "$ITEMS_AFTER"
        cat "$ITEMS_AFTER"
        echo ">>>>>>>>>>>>>>>>>>>>>>"
        ls -al
        echo ">>>>>>>>>>>>>>>>>>>>>>Replace the site-packages with the new one"
        ITEMS_DIFF=$(comm -13 "$ITEMS_BEFORE" "$ITEMS_AFTER")
        echo ">>>>>>>>>>>>>>>>>>>>>> Items diff"
        echo $ITEMS_DIFF
        echo ">>>>>>>>>>>>>>>>>>>>>>"
        cd ../..
        pwd
        tree -L 2
        mv ./site-packages ./temp/site-packages-bk
        tree -L 2
        mkdir -p ./site-packages
        tree -L 2
        echo ">>>>>>>>>>>>>>>>>>>>>> copy the new site-packages"
        for item in $ITEMS_DIFF; do
          cp -r "$SITE_PACKAGES/$item" ./site-packages
        done
        echo ">>>>>>>>>>>>>>>>>>>>>> check the new site-packages"
        tree -L 2
        rm -rf ./temp
      # cp -r $SITE_PACKAGES/* ./site-packages/
      # tree -L 1



    - name: Commit and push changes
      run: |
        git config --local user.email "mingjing@merico.dev"
        git config --local user.name "Update-Packages Action"
        BRANCH_NAME=update-packages-$(date +'%Y%m%d-%H%M%S')
        git checkout -b $BRANCH_NAME
        git add ./site-packages
        git commit -m "Update devchat site-packages"
        git status
        git push origin $BRANCH_NAME
        echo "BRANCH_NAME=$BRANCH_NAME" >> "$GITHUB_ENV"

    - name: Create Pull Request
      run: |
        gh pr create \
          --title "Sync up devchat packages from branch $BRANCH_NAME" \
          --body "This PR is auto-generated by GitHub Action. It syncs up the devchat packages." \
          --base main \
          --head $BRANCH_NAME
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v6
    #   with:
    #     title: "Sync up devchat packages from branch ${{ env.BRANCH_NAME }}"
    #     branch: ${{ env.BRANCH_NAME }}
    #     base: main
    #     body: "This PR is auto-generated by GitHub Action. It syncs up the devchat packages from the devchat repository."

    # - name: Push changes
    #   run: |
    #     git push origin new-branch

    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v3
    #   with:
    #     title: "Sync up devchat packages"
    #     branch: "new-branch"
    #     body: "This PR is auto-generated by GitHub Action. It syncs up the devchat packages."