name: Sync up devchat packages

on:
  # workflow_dispatch:
  push:
    branches:
      - ci

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: main

    # - name: Create new branch
    #   run: |
    #     git checkout -b new-branch

    - name: Install micromamba
      run: |
        wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba
        ./bin/micromamba shell init -s bash -p ~/micromamba
        source ~/.bashrc
        micromamba create -y -n devchat_no_binary python=3.8
        micromamba activate devchat_no_binary
  
    - name: Checkout devchat repository to a temporary directory
      uses: actions/checkout@v2
      with:
        repository: devchat-ai/devchat
        path: ./temp-devchat
    
    - name: Run script
      run: |
        cd ./temp-devchat
        pip list
        pip install typer
        pip list
        

    # - name: Commit changes
    #   run: |
    #     git config --local user.email "action@github.com"
    #     git config --local user.name "GitHub Action"
    #     git commit -am "Sync up devchat packages"

    # - name: Push changes
    #   run: |
    #     git push origin new-branch

    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v3
    #   with:
    #     title: "Sync up devchat packages"
    #     branch: "new-branch"
    #     body: "This PR is auto-generated by GitHub Action. It syncs up the devchat packages."